;;; org-foresight-demo.el --- Generated data to develop against  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 yoshzucker

;; Author: yoshzucker
;; URL: https://github.com/yoshzucker/org-foresight

;; This file is not part of GNU Emacs.

;;; Commentary:

;; A working day, generated.  Not loaded by `org-foresight' -- it exists so the
;; package can be developed and demonstrated on a machine that has no real
;; data, or has data too sensitive to experiment on.
;;
;; Two decisions shape it:
;;
;; Dates are computed, never written down.  A fixture with literal dates is
;; correct on the day it is written and misleading forever after; "today's
;; capacity" cannot be checked against a file that thinks today is last week.
;; `org-foresight-demo-regenerate' rewrites everything relative to now, so it
;; is always the right shape, and re-running it is the way to get back to a
;; known state after experimenting.
;;
;; The data lives apart from the real files and is reached by a toggle.  Mixing
;; invented tasks into a real agenda is precisely the failure this package's
;; own agenda-file hygiene exists to prevent: fabricated clock entries would
;; silently enter every report and every learned average.  So
;; `org-foresight-demo-mode' swaps `org-agenda-files' (and the file generated
;; tasks are written to) for the session, and swaps them back.

;;; Code:

(require 'org)
(require 'org-foresight-core)

(defgroup org-foresight-demo nil
  "Generated data for developing org-foresight."
  :group 'org-foresight
  :prefix "org-foresight-demo-")

(defcustom org-foresight-demo-directory
  (locate-user-emacs-file "org-foresight-demo/")
  "Where the generated demo files are written.
Machine-local and disposable: everything in it is rewritten by
`org-foresight-demo-regenerate'."
  :type 'directory
  :group 'org-foresight-demo)

(defvar org-foresight-demo--saved nil
  "State captured when `org-foresight-demo-mode' was switched on.")

;;;; Date helpers
;; Everything below is expressed as an offset from today, so the generated
;; files describe the same *situation* whenever they are made.

(defun org-foresight-demo--time (offset &optional hh mm)
  "Return the time OFFSET days from today, at HH:MM (default midnight)."
  (let ((d (decode-time (time-add (org-foresight--day-start 0)
                                  (days-to-time offset)))))
    (encode-time 0 (or mm 0) (or hh 0) (nth 3 d) (nth 4 d) (nth 5 d))))

(defun org-foresight-demo--date (offset)
  "Return \"YYYY-MM-DD Day\" for OFFSET days from today."
  (format-time-string "%Y-%m-%d %a" (org-foresight-demo--time offset)))

(defun org-foresight-demo--stamp (offset &optional from to repeater)
  "Return an active timestamp OFFSET days out.
FROM and TO are \"HH:MM\" strings; REPEATER is e.g. \"+1w\"."
  (concat "<" (org-foresight-demo--date offset)
          (when from (concat " " from))
          (when (and from to) (concat "-" to))
          (when repeater (concat " " repeater))
          ">"))

(defun org-foresight-demo--inactive (offset &optional hh mm)
  "Return an inactive timestamp OFFSET days out at HH:MM."
  (format-time-string "[%Y-%m-%d %a %H:%M]"
                      (org-foresight-demo--time offset (or hh 9) (or mm 0))))

(defun org-foresight-demo--clock (offset from-hh from-mm to-hh to-mm)
  "Return a CLOCK line OFFSET days out, with its duration filled in."
  (let ((mins (- (+ (* 60 to-hh) to-mm) (+ (* 60 from-hh) from-mm))))
    (format "CLOCK: %s--%s => %s"
            (org-foresight-demo--inactive offset from-hh from-mm)
            (org-foresight-demo--inactive offset to-hh to-mm)
            (format "%d:%02d" (/ mins 60) (mod mins 60)))))

(defun org-foresight-demo--weekday (offset)
  "Return the first offset at or after OFFSET that lands on a working day."
  (let ((n offset))
    (while (not (memq (nth 6 (decode-time (org-foresight-demo--time n)))
                      org-foresight-workdays))
      (setq n (1+ n)))
    n))

;;;; The generated files

(defun org-foresight-demo--calendar ()
  "Return the contents of the demo calendar.
Shaped like the output of an ics import: every event carries a UID and a
CATEGORY, because that is what the meeting signal keys on."
  (let ((d1 (org-foresight-demo--weekday 1))
        (d2 (org-foresight-demo--weekday 2))
        (d3 (org-foresight-demo--weekday 3))
        (d5 (org-foresight-demo--weekday 5)))
    (concat
     "#+title: Calendar (demo)\n"
     "# Generated by org-foresight-demo-regenerate.  Edits will be lost.\n\n"

     ;; A call: its location says where to dial in, not where to be, so it
     ;; must not produce a journey.
     "* Morning standup\n:PROPERTIES:\n:UID: demo-standup\n"
     ":CATEGORY: outlook\n:LOCATION: https://teams.microsoft.com/l/demo\n:END:\n"
     (org-foresight-demo--stamp 0 "09:30" "09:45") "\n\n"

     ;; The expensive one: an hour at the office, plus the journey either way.
     "* Project review\n:PROPERTIES:\n:UID: demo-review\n"
     ":CATEGORY: outlook\n:LOCATION: 本社 会議室A\n:END:\n"
     (org-foresight-demo--stamp 0 "14:00" "15:30") "\n\n"

     "* Vendor workshop\n:PROPERTIES:\n:UID: demo-workshop\n"
     ":CATEGORY: outlook\n:LOCATION: 顧客様先\n:END:\n"
     (org-foresight-demo--stamp d1 "09:00" "12:00") "\n\n"

     ;; A private commitment: it fills the evening but is not borrowed work.
     "* Dinner with the family\n:PROPERTIES:\n:UID: demo-dinner\n"
     ":CATEGORY: family\n:END:\n"
     (org-foresight-demo--stamp 0 "19:00" "20:30") "\n\n"

     ;; A repeater: proves the scan projects it across the whole horizon.
     "* Weekly sync\n:PROPERTIES:\n:UID: demo-sync\n"
     ":CATEGORY: outlook\n:END:\n"
     (org-foresight-demo--stamp d2 "16:00" "17:00" "+1w") "\n\n"

     ;; Outside the working window: subtracted from nothing, warned about by
     ;; nothing -- which is why the After hours signal exists.
     "* Overseas call\n:PROPERTIES:\n:UID: demo-overseas\n"
     ":CATEGORY: outlook\n:END:\n"
     (org-foresight-demo--stamp d3 "19:00" "20:00") "\n\n"

     ;; Already handled: must NOT appear in the meeting signal.
     "* Budget meeting\n:PROPERTIES:\n:UID: demo-budget\n"
     ":CATEGORY: outlook\n:PLAN_PREP: t\n:END:\n"
     (org-foresight-demo--stamp d5 "11:00" "12:00") "\n\n"

     ;; A different category, and all-day: implies no preparation, and must not
     ;; swallow the working day either.
     "* Club practice\n:PROPERTIES:\n:UID: demo-club\n"
     ":CATEGORY: club\n:END:\n"
     (org-foresight-demo--stamp 2) "\n")))

(defun org-foresight-demo--datetree (blocks)
  "Render BLOCKS, an alist of (OFFSET . ENTRIES), as a date tree.
Year and month headings are emitted when they change rather than assumed, so
a demo generated on the first of a month still produces a well-formed tree."
  (let (out (year nil) (month nil))
    (pcase-dolist (`(,offset . ,entries)
                   (sort (copy-sequence blocks)
                         (lambda (a b) (< (car a) (car b)))))
      (let* ((time (org-foresight-demo--time offset))
             (y (format-time-string "%Y" time))
             (m (format-time-string "%Y-%m %B" time)))
        (unless (equal y year)
          (setq year y month nil)
          (push (concat "* " y "\n") out))
        (unless (equal m month)
          (setq month m)
          (push (concat "** " m "\n") out))
        (push (concat "*** " (org-foresight-demo--date offset) "\n") out)
        (dolist (e entries) (push e out))))
    (apply #'concat (nreverse out))))

(defun org-foresight-demo--tasks ()
  "Return the contents of the demo task file.
A date tree, matching where generated tasks are filed, and carrying one
example of every situation the signals look for."
  (let* ((d1 (org-foresight-demo--weekday 1))
         (d3 (org-foresight-demo--weekday 3))
         (d6 (org-foresight-demo--weekday 6)))
    (concat
     "#+title: Tasks (demo)\n"
     "# Generated by org-foresight-demo-regenerate.  Edits will be lost.\n\n"
     (org-foresight-demo--datetree
      (cons
       (cons 0 (list (concat
     ;; --- today: placed work, so the day has real busy intervals ---------
     ;; Deliberately left where the afternoon's commute runs over it: a day
     ;; that cannot physically happen is exactly what the clash signal is for,
     ;; and the demo should contain one.
     "**** NEXT Draft the quarterly summary\n"
     "SCHEDULED: " (org-foresight-demo--stamp 0 "13:00") "\n"
     ":PROPERTIES:\n:EFFORT:   1:00\n:CATEGORY: reporting\n:END:\n"

     ;; --- today: promised but unplaced, so `promised' is non-zero --------
     "**** NEXT Reply to the procurement thread\n"
     "SCHEDULED: " (org-foresight-demo--stamp 0) "\n"
     ":PROPERTIES:\n:EFFORT:   0:30\n:CATEGORY: admin\n:END:\n"

     "**** NEXT Review the migration plan\n"
     "SCHEDULED: " (org-foresight-demo--stamp 0) "\n"
     ":PROPERTIES:\n:EFFORT:   1:30\n:CATEGORY: engineering\n:END:\n"

     ;; --- today: clocked work, so Clocked/Estimate have something --------
     "**** DONE Fix the nightly build\n"
     "CLOSED: " (org-foresight-demo--inactive 0 11 30) "\n"
     ":PROPERTIES:\n:EFFORT:   1:00\n:CATEGORY: engineering\n:END:\n"
     ":LOGBOOK:\n" (org-foresight-demo--clock 0 10 15 11 30) "\n:END:\n"

     "**** ONGO Investigate the latency report\n"
     ":PROPERTIES:\n:EFFORT:   2:00\n:CATEGORY: engineering\n:END:\n"
     ":LOGBOOK:\n" (org-foresight-demo--clock 0 15 45 16 40) "\n:END:\n"

     ;; --- the signals ----------------------------------------------------
     ;; Kept moving: four reschedules, written the way org-log-reschedule does.
     "**** NEXT Write the vendor comparison\n"
     "SCHEDULED: " (org-foresight-demo--stamp 0) "\n"
     ":PROPERTIES:\n:EFFORT:   2:00\n:CATEGORY: procurement\n:END:\n"
     ":LOGBOOK:\n"
     "- Rescheduled from \"" (org-foresight-demo--inactive -8) "\" on "
     (org-foresight-demo--inactive -7) "\n"
     "- Rescheduled from \"" (org-foresight-demo--inactive -7) "\" on "
     (org-foresight-demo--inactive -5) "\n"
     "- Rescheduled from \"" (org-foresight-demo--inactive -5) "\" on "
     (org-foresight-demo--inactive -3) "\n"
     "- Rescheduled from \"" (org-foresight-demo--inactive -3) "\" on "
     (org-foresight-demo--inactive -1) "\n"
     ":END:\n"

     ;; Unplannable: a near deadline with nothing to place.
     "**** NEXT Prepare the board pack\n"
     "DEADLINE: " (org-foresight-demo--stamp d3) "\n"
     ":PROPERTIES:\n:CATEGORY: reporting\n:END:\n"

     ;; Orphaned prep: points at a meeting no longer in the calendar.
     "**** NEXT Prep: Cancelled kickoff\n"
     "SCHEDULED: " (org-foresight-demo--stamp d1) "\n"
     ":PROPERTIES:\n:EFFORT:   0:30\n:PLAN_MEETING_UID: demo-cancelled\n:END:\n"

     ;; Gone quiet: both keywords, both overdue.
     "**** WAIT Legal sign-off on the contract\n"
     "SCHEDULED: " (org-foresight-demo--stamp -4) "\n"
     ":PROPERTIES:\n:CATEGORY: procurement\n:END:\n"

     "**** DELEG Onboarding checklist for the new starter\n"
     "SCHEDULED: " (org-foresight-demo--stamp -2) "\n"
     ":PROPERTIES:\n:DELEGATED_TO: Sato\n:CATEGORY: team\n:END:\n"

     ;; --- unscheduled work: the candidates Phase 4 will place ------------
     "**** NEXT Update the runbook\n"
     ":PROPERTIES:\n:EFFORT:   0:45\n:CATEGORY: engineering\n:END:\n"

     "**** NEXT Chase the invoice\n"
     ":PROPERTIES:\n:EFFORT:   0:15\n:CATEGORY: admin\n:END:\n"

     "**** NEXT Draft next quarter's objectives\n"
     "DEADLINE: " (org-foresight-demo--stamp d6) "\n"
     ":PROPERTIES:\n:EFFORT:   2:00\n:CATEGORY: reporting\n:END:\n"

     "**** NEXT Tidy the shared drive\n"
     ":PROPERTIES:\n:EFFORT:   0:30\n:CATEGORY: admin\n:END:\n"

     ;; Started but unfinished, several at once: the switching cost is what
     ;; makes a day that looks reasonable run long.
     "**** ONGO Refactor the import pipeline\n"
     ":PROPERTIES:\n:EFFORT:   3:00\n:CATEGORY: engineering\n:END:\n"
     "**** ONGO Chase the security review\n"
     ":PROPERTIES:\n:EFFORT:   1:00\n:CATEGORY: admin\n:END:\n"

     ;; Promised for today and far too big for anything left of it.
     "**** NEXT Rewrite the annual report\n"
     "SCHEDULED: " (org-foresight-demo--stamp 0) "\n"
     ":PROPERTIES:\n:EFFORT:   6:00\n:CATEGORY: reporting\n:END:\n"

     ;; Captured and never decided about: no state, no date, no clock.
     "**** Something I wondered about on the train\n")))
       ;; --- history: gives the week review and the vs-7d comparison data --
       (org-foresight-demo--history))))))

(defun org-foresight-demo--history ()
  "Return (OFFSET . ENTRIES) blocks for the past week, with clock data.

Enough spread across categories and days that the weekly review, the daily
share table and the vs-7-day comparison all have something to show.

The estimates are deliberately not the outcomes.  Each segment records what
was thought beforehand alongside what it actually took, with reporting work
running consistently over -- which is what gives `org-foresight-learn-bias'
something real to find."
  (let ((plan '((-1 ("engineering" 9 15 12 0 1.0) ("admin" 13 30 15 0 1.0))
                (-2 ("reporting" 10 0 12 30 0.6) ("engineering" 14 0 16 45 0.9))
                (-3 ("admin" 9 30 10 15 1.0) ("procurement" 11 0 12 0 1.0))
                (-4 ("engineering" 9 0 11 30 0.9) ("team" 15 0 16 0 1.0))
                (-5 ("reporting" 10 30 12 0 0.6))
                (-6 ("engineering" 13 0 17 0 0.9))
                (-7 ("admin" 9 0 10 30 1.0) ("reporting" 11 0 13 0 0.6)))))
    (mapcar
     (lambda (day)
       (let ((offset (car day)))
         (cons offset
               (mapcar
                (lambda (seg)
                  (pcase-let* ((`(,cat ,fh ,fm ,th ,tm ,accuracy) seg)
                               (actual (- (+ (* 60 th) tm) (+ (* 60 fh) fm)))
                               (est (round (* actual accuracy))))
                    (concat
                     (format "**** DONE %s work, %s\n"
                             (capitalize cat) (org-foresight-demo--date offset))
                     "CLOSED: " (org-foresight-demo--inactive offset th tm) "\n"
                     ":PROPERTIES:\n"
                     (format ":EFFORT:   %d:%02d\n" (/ est 60) (mod est 60))
                     (format ":CATEGORY: %s\n" cat)
                     ":END:\n:LOGBOOK:\n"
                     (org-foresight-demo--clock offset fh fm th tm) "\n:END:\n")))
                (cdr day)))))
     plan)))

;;;; Commands

(defun org-foresight-demo-files ()
  "Return the demo files, as a list of absolute paths."
  (mapcar (lambda (n) (expand-file-name n org-foresight-demo-directory))
          '("calendar.org" "tasks.org")))

;;;###autoload
(defun org-foresight-demo-regenerate ()
  "Write the demo files afresh, dated relative to today.
Also the way back to a known state: anything done to the demo data -- tasks
filed, meetings prepared, entries rescheduled -- is undone by regenerating."
  (interactive)
  (make-directory org-foresight-demo-directory t)
  (pcase-dolist (`(,name . ,fn)
                 `(("calendar.org" . ,#'org-foresight-demo--calendar)
                   ("tasks.org" . ,#'org-foresight-demo--tasks)))
    (let ((path (expand-file-name name org-foresight-demo-directory)))
      (when-let ((buf (get-file-buffer path)))
        (with-current-buffer buf (set-buffer-modified-p nil))
        (kill-buffer buf))
      (with-temp-file path (insert (funcall fn)))))
  (when (called-interactively-p 'interactive)
    (message "Demo data regenerated in %s" org-foresight-demo-directory))
  (org-foresight-demo-files))

;;;###autoload
(define-minor-mode org-foresight-demo-mode
  "Point the agenda at generated demo data instead of the real files.

Switching on regenerates the data, redirects `org-agenda-files' and the file
generated tasks are written to, and drops any cached surge reserve so the
figures come from the demo alone.  Switching off puts all of it back.

The redirection is the point: experimenting against real files would leave
invented clock entries in the history that every later average is computed
from, and there is no undo for that."
  :global t
  :group 'org-foresight-demo
  :lighter " Foresight-demo"
  (if org-foresight-demo-mode
      (progn
        (setq org-foresight-demo--saved
              (list :agenda-files (bound-and-true-p org-agenda-files)
                    :task-file (bound-and-true-p org-foresight-task-file)
                    :day-file (bound-and-true-p org-foresight-day-file)
                    :surge-cache org-foresight-surge-cache-file
                    :bias-cache org-foresight-bias-cache-file))
        (org-foresight-demo-regenerate)
        (setq org-agenda-files (org-foresight-demo-files))
        (let ((tasks (expand-file-name "tasks.org" org-foresight-demo-directory)))
          (when (boundp 'org-foresight-task-file)
            (setq org-foresight-task-file tasks))
          (when (boundp 'org-foresight-day-file)
            (setq org-foresight-day-file tasks)))
        ;; Learned figures are redirected too: a reserve or a multiplier taken
        ;; from real history would describe a different life than the demo's.
        (setq org-foresight-surge-cache-file
              (expand-file-name "surge.eld" org-foresight-demo-directory)
              org-foresight-bias-cache-file
              (expand-file-name "bias.eld" org-foresight-demo-directory))
        (setq org-foresight--shape-cache nil
              org-foresight--bias-cache nil)
        (message "Demo data active (%d files); C-c a a to look"
                 (length (org-foresight-demo-files))))
    (setq org-agenda-files (plist-get org-foresight-demo--saved :agenda-files))
    (when (boundp 'org-foresight-task-file)
      (setq org-foresight-task-file
            (plist-get org-foresight-demo--saved :task-file)))
    (when (boundp 'org-foresight-day-file)
      (setq org-foresight-day-file
            (plist-get org-foresight-demo--saved :day-file)))
    (setq org-foresight-surge-cache-file
          (plist-get org-foresight-demo--saved :surge-cache)
          org-foresight-bias-cache-file
          (plist-get org-foresight-demo--saved :bias-cache))
    (setq org-foresight--shape-cache nil
          org-foresight--bias-cache nil)
    (message "Demo data off; agenda back to the real files")))

(provide 'org-foresight-demo)

;;; org-foresight-demo.el ends here
